name: 🧪 API Tests & Allure Report

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"  # 1:00 AM CST (7:00 AM UTC)

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests with Allure
        env:
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_COMPANY: ${{ secrets.USER_COMPANY }}
        run: dotnet test --settings:ApiTestingDemo.Tests/test.runsettings

      - name: Copy categories to allure-results
        if: always()
        run: cp ApiTestingDemo.Tests/categories.json allure-results/categories.json

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 30

      - name: Checkout gh-pages for history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy previous Allure history
        if: always()
        run: |
          if [ -d "gh-pages/allure-report/history" ]; then
            mkdir -p allure-results/history
            cp -r gh-pages/allure-report/history/* allure-results/history/
          fi

      - name: Setup Java (required for Allure)
        if: always()
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Allure CLI via npm
        if: always()
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        if: always()
        run: allure generate allure-results -o allure-report --clean

      - name: Generate Single-File Allure Report
        if: always()
        run: allure generate allure-results -o allure-single-file --single-file --clean

      - name: Upload Single-File HTML report as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-single-file-report
          path: allure-single-file/index.html
          retention-days: 30

      - name: Upload Allure HTML report as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report
          retention-days: 30

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          keep_files: false
          enable_jekyll: false
